n = int(input('Digite um valor: '))
print(f'O valor escolhido foi: {n}.')
print(f'O dobro desse valor é: {n * 2}')
print(f'O triplo desse valor é: {n * 3}.')
print(f'A raíz quadrada desse valor é: {n ** (1/2):.2f}')
